version: "3.9"

services:
  bot:
    build: .
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app
      - sales_bot_admin_media_data:/media

networks:
  default:
    external:
      name: backend

volumes:
  sales_bot_admin_media_data:
    external: true